[package]
name = "containicus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
env_logger = "0.11.9"
log = "0.4.29"
regex = "1.12.3"
regex-macro = "0.3.0"
